### ISSUE TITLE
Setup CI to run test scripts

### ISSUE THREAD

**Issue by kalouantonis** [bas080/projector#18]
We could use CircleCI or TravisCI for this, I'm willing to set this up but you'll need to sign up for one of them.

**Comment by bas080** [comment]
#19. 

Runs the `./script/tests`. Looks like travis is giving the green light.

**Comment by kalouantonis** [comment]
There's still some issues with the CI AFAIK, as commented on PR #20. After that's fixed i'll close the issue.

**Comment by bas080** [comment]
I can fix it by merging the travis CI branch first. I would expect travis to not run tests if the travis config file is not present. Yet it did.

**Comment by kalouantonis** [comment]
Ah, that makes sense. You can close it when its merged then.
