### ISSUE TITLE
Notify user when and what .bash_project file is sourced

### ISSUE THREAD

**Issue by bas080** [bas080/projector#9]
As a user it's nice to know when and what .bash_project file is sourced.

**Comment by kalouantonis** [comment]
I'm not sure this adds much value to be honest, it will just add noise to the terminal IMO.

For example

```
$ cd project
==> .bash_project sourced
$ cd child
$cd ..
==> .bash_project sourced
```

**Comment by bas080** [comment]
It will only source when the child also has a `.bash_project`. You can also cd to the child directly and it'll source the .bash_project in the parent directory.

**Comment by bas080** [comment]
#10
